//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinFinder.WebServiceTestClient.TwinFinderWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareDefinitionGroup", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.Compare")]
    [System.SerializableAttribute()]
    public partial class CompareDefinitionGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinFinder.WebServiceTestClient.TwinFinderWebservice.Aggregator AggregatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareDefinition> CompareDefinitionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinFinder.WebServiceTestClient.TwinFinderWebservice.Aggregator Aggregator {
            get {
                return this.AggregatorField;
            }
            set {
                if ((object.ReferenceEquals(this.AggregatorField, value) != true)) {
                    this.AggregatorField = value;
                    this.RaisePropertyChanged("Aggregator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareDefinition> CompareDefinitions {
            get {
                return this.CompareDefinitionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CompareDefinitionsField, value) != true)) {
                    this.CompareDefinitionsField = value;
                    this.RaisePropertyChanged("CompareDefinitions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aggregator", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ag" +
        "gregators.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.AverageAggregator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.HarmonicMeanAggregator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.MaximumAggregator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.MinimumAggregator))]
    public partial class Aggregator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareDefinition", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.Compare")]
    [System.SerializableAttribute()]
    public partial class CompareDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinFinder.WebServiceTestClient.TwinFinderWebservice.Aggregator AggregatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareField> CompareFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareField> StopFieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinFinder.WebServiceTestClient.TwinFinderWebservice.Aggregator Aggregator {
            get {
                return this.AggregatorField;
            }
            set {
                if ((object.ReferenceEquals(this.AggregatorField, value) != true)) {
                    this.AggregatorField = value;
                    this.RaisePropertyChanged("Aggregator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareField> CompareFields {
            get {
                return this.CompareFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.CompareFieldsField, value) != true)) {
                    this.CompareFieldsField = value;
                    this.RaisePropertyChanged("CompareFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareField> StopFields {
            get {
                return this.StopFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.StopFieldsField, value) != true)) {
                    this.StopFieldsField = value;
                    this.RaisePropertyChanged("StopFields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AverageAggregator", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ag" +
        "gregators")]
    [System.SerializableAttribute()]
    public partial class AverageAggregator : TwinFinder.WebServiceTestClient.TwinFinderWebservice.Aggregator {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HarmonicMeanAggregator", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ag" +
        "gregators")]
    [System.SerializableAttribute()]
    public partial class HarmonicMeanAggregator : TwinFinder.WebServiceTestClient.TwinFinderWebservice.Aggregator {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaximumAggregator", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ag" +
        "gregators")]
    [System.SerializableAttribute()]
    public partial class MaximumAggregator : TwinFinder.WebServiceTestClient.TwinFinderWebservice.Aggregator {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinimumAggregator", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ag" +
        "gregators")]
    [System.SerializableAttribute()]
    public partial class MinimumAggregator : TwinFinder.WebServiceTestClient.TwinFinderWebservice.Aggregator {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareField", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.Compare")]
    [System.SerializableAttribute()]
    public partial class CompareField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> FieldConvertersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer FuzzyComparerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> FieldConverters {
            get {
                return this.FieldConvertersField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldConvertersField, value) != true)) {
                    this.FieldConvertersField = value;
                    this.RaisePropertyChanged("FieldConverters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer FuzzyComparer {
            get {
                return this.FuzzyComparerField;
            }
            set {
                if ((object.ReferenceEquals(this.FuzzyComparerField, value) != true)) {
                    this.FuzzyComparerField = value;
                    this.RaisePropertyChanged("FuzzyComparer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name1 {
            get {
                return this.Name1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name1Field, value) != true)) {
                    this.Name1Field = value;
                    this.RaisePropertyChanged("Name1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name2 {
            get {
                return this.Name2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name2Field, value) != true)) {
                    this.Name2Field = value;
                    this.RaisePropertyChanged("Name2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringFuzzyComparer", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ba" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.ExtendedEditex))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.JaroWinkler))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.DiceCoefficent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.MongeElkan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.NGramDistance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.SmithWaterman))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.Identity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.ExtendedJaccard))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.DamerauLevenshteinDistance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.NameComparer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.CityComparer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompanyComparer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.PhoneComparer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.TitleComparer))]
    public partial class StringFuzzyComparer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringCostFunction CostFunctionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringCostFunction CostFunction {
            get {
                return this.CostFunctionField;
            }
            set {
                if ((object.ReferenceEquals(this.CostFunctionField, value) != true)) {
                    this.CostFunctionField = value;
                    this.RaisePropertyChanged("CostFunction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringCostFunction", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.St" +
        "ringCostFunctions.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.DefaultSubstitutionCostFunction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.CharGroupsSubstitutionCostFunction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinFinder.WebServiceTestClient.TwinFinderWebservice.SmithWatermanCostFunction))]
    public partial class StringCostFunction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedEditex", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class ExtendedEditex : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer FuzzyComparerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer FuzzyComparer {
            get {
                return this.FuzzyComparerField;
            }
            set {
                if ((object.ReferenceEquals(this.FuzzyComparerField, value) != true)) {
                    this.FuzzyComparerField = value;
                    this.RaisePropertyChanged("FuzzyComparer");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JaroWinkler", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class JaroWinkler : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiceCoefficent", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class DiceCoefficent : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MongeElkan", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class MongeElkan : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer FuzzyComparerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseSpecialAbbreviationCheckField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer FuzzyComparer {
            get {
                return this.FuzzyComparerField;
            }
            set {
                if ((object.ReferenceEquals(this.FuzzyComparerField, value) != true)) {
                    this.FuzzyComparerField = value;
                    this.RaisePropertyChanged("FuzzyComparer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseSpecialAbbreviationCheck {
            get {
                return this.UseSpecialAbbreviationCheckField;
            }
            set {
                if ((this.UseSpecialAbbreviationCheckField.Equals(value) != true)) {
                    this.UseSpecialAbbreviationCheckField = value;
                    this.RaisePropertyChanged("UseSpecialAbbreviationCheck");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NGramDistance", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class NGramDistance : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NGramLengthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NGramLength {
            get {
                return this.NGramLengthField;
            }
            set {
                if ((this.NGramLengthField.Equals(value) != true)) {
                    this.NGramLengthField = value;
                    this.RaisePropertyChanged("NGramLength");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmithWaterman", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class SmithWaterman : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identity", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class Identity : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedJaccard", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class ExtendedJaccard : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer FuzzyComparerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer FuzzyComparer {
            get {
                return this.FuzzyComparerField;
            }
            set {
                if ((object.ReferenceEquals(this.FuzzyComparerField, value) != true)) {
                    this.FuzzyComparerField = value;
                    this.RaisePropertyChanged("FuzzyComparer");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DamerauLevenshteinDistance", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Co" +
        "mmon")]
    [System.SerializableAttribute()]
    public partial class DamerauLevenshteinDistance : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameComparer", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ad" +
        "dressSpecific")]
    [System.SerializableAttribute()]
    public partial class NameComparer : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityComparer", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ad" +
        "dressSpecific")]
    [System.SerializableAttribute()]
    public partial class CityComparer : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyComparer", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ad" +
        "dressSpecific")]
    [System.SerializableAttribute()]
    public partial class CompanyComparer : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneComparer", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ad" +
        "dressSpecific")]
    [System.SerializableAttribute()]
    public partial class PhoneComparer : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TitleComparer", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.Ad" +
        "dressSpecific")]
    [System.SerializableAttribute()]
    public partial class TitleComparer : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringFuzzyComparer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefaultSubstitutionCostFunction", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.St" +
        "ringCostFunctions")]
    [System.SerializableAttribute()]
    public partial class DefaultSubstitutionCostFunction : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringCostFunction {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharGroupsSubstitutionCostFunction", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.St" +
        "ringCostFunctions")]
    [System.SerializableAttribute()]
    public partial class CharGroupsSubstitutionCostFunction : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringCostFunction {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmithWatermanCostFunction", Namespace="http://schemas.datacontract.org/2004/07/TwinFinder.Matching.StringFuzzyCompare.St" +
        "ringCostFunctions")]
    [System.SerializableAttribute()]
    public partial class SmithWatermanCostFunction : TwinFinder.WebServiceTestClient.TwinFinderWebservice.StringCostFunction {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TwinFinderWebservice.ITwinFinderWebService")]
    public interface ITwinFinderWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwinFinderWebService/CompareRecords", ReplyAction="http://tempuri.org/ITwinFinderWebService/CompareRecordsResponse")]
        float CompareRecords(string sessionKey, System.Collections.Generic.Dictionary<string, string> record1, System.Collections.Generic.Dictionary<string, string> record2, TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareDefinitionGroup compareDefinitionGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwinFinderWebService/CompareRecords", ReplyAction="http://tempuri.org/ITwinFinderWebService/CompareRecordsResponse")]
        System.Threading.Tasks.Task<float> CompareRecordsAsync(string sessionKey, System.Collections.Generic.Dictionary<string, string> record1, System.Collections.Generic.Dictionary<string, string> record2, TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareDefinitionGroup compareDefinitionGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwinFinderWebService/CreateSession", ReplyAction="http://tempuri.org/ITwinFinderWebService/CreateSessionResponse")]
        string CreateSession(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwinFinderWebService/CreateSession", ReplyAction="http://tempuri.org/ITwinFinderWebService/CreateSessionResponse")]
        System.Threading.Tasks.Task<string> CreateSessionAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwinFinderWebService/CloseSession", ReplyAction="http://tempuri.org/ITwinFinderWebService/CloseSessionResponse")]
        void CloseSession(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwinFinderWebService/CloseSession", ReplyAction="http://tempuri.org/ITwinFinderWebService/CloseSessionResponse")]
        System.Threading.Tasks.Task CloseSessionAsync(string sessionKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITwinFinderWebServiceChannel : TwinFinder.WebServiceTestClient.TwinFinderWebservice.ITwinFinderWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwinFinderWebServiceClient : System.ServiceModel.ClientBase<TwinFinder.WebServiceTestClient.TwinFinderWebservice.ITwinFinderWebService>, TwinFinder.WebServiceTestClient.TwinFinderWebservice.ITwinFinderWebService {
        
        public TwinFinderWebServiceClient() {
        }
        
        public TwinFinderWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwinFinderWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwinFinderWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwinFinderWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float CompareRecords(string sessionKey, System.Collections.Generic.Dictionary<string, string> record1, System.Collections.Generic.Dictionary<string, string> record2, TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareDefinitionGroup compareDefinitionGroup) {
            return base.Channel.CompareRecords(sessionKey, record1, record2, compareDefinitionGroup);
        }
        
        public System.Threading.Tasks.Task<float> CompareRecordsAsync(string sessionKey, System.Collections.Generic.Dictionary<string, string> record1, System.Collections.Generic.Dictionary<string, string> record2, TwinFinder.WebServiceTestClient.TwinFinderWebservice.CompareDefinitionGroup compareDefinitionGroup) {
            return base.Channel.CompareRecordsAsync(sessionKey, record1, record2, compareDefinitionGroup);
        }
        
        public string CreateSession(string userName, string password) {
            return base.Channel.CreateSession(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> CreateSessionAsync(string userName, string password) {
            return base.Channel.CreateSessionAsync(userName, password);
        }
        
        public void CloseSession(string sessionKey) {
            base.Channel.CloseSession(sessionKey);
        }
        
        public System.Threading.Tasks.Task CloseSessionAsync(string sessionKey) {
            return base.Channel.CloseSessionAsync(sessionKey);
        }
    }
}
